ENH: support variable copyright dates
qiime2/q2lint pull request #15
Opened 2017-08-16 22:20 UTC by ebolyen

2017-08-16 22:22 UTC, ebolyen commented
Tested on q2lint a couple of ways, example of output:
```
Invalid header: q2lint/_main.py (incorrect copyright years or does not match reference)
```

```
Invalid LICENSE file (incorrect copyright years or does not match reference)
Invalid header: q2lint/_main.py (incorrect copyright years or does not match reference)
```

plain mismatch:
```
Invalid LICENSE file (does not match reference)
Invalid header: q2lint/_main.py (does not match reference)
```

2017-08-17 18:00 UTC, jairideout requested changes
Looks great @ebolyen! Just had one comment.

2017-08-17 18:00 UTC, jairideout commented on q2lint/_main.py
> +    for idx, (line, ref) in enumerate(zip(license.splitlines(),
I think we should use `itertools.zip_longest` so that the loop doesn't terminate early if one license is shorter than the other.

2017-08-17 18:04 UTC, ebolyen commented on q2lint/_main.py
> +    for idx, (line, ref) in enumerate(zip(license.splitlines(),
Good catch!

2017-08-17 18:23 UTC, jairideout approved these changes
Thanks @ebolyen!

2017-08-17 18:24 UTC, merged